# Generated by Django 4.2.4 on 2024-10-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('animal', models.CharField(max_length=255)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('habitat', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField()),
                ('formation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('moderator_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_category',
                'managed': False,
            },
        ),
    ]
